### PR TITLE
Update course field in an application to be an object

### PR DESCRIPTION
**Pull request by chubberlisk**
### Context

Currently in our `Application` resource, it has a `condition` field that contains an array of `Course`s. This suggests that a provider will know the other courses a candidate has applied for.

### Changes proposed in this pull request

Update `course` field in the `Application` resource to be an object instead of an array of `Course`s.

### Guidance to review

Double check this is the only change required.

### Link to Trello card

[903 - Update Application resource to only contain a single course in the API docs](https://trello.com/c/KbTOtGVJ/903-update-application-resource-to-only-contain-a-single-course-in-the-api-docs)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
@benilovj this changes the API to return one and only one course per application, which we believe is the correct behaviour. (i.e. Even if a candidate has applied to two courses on the same provider, this should result in two separate applications from the provider's POV)

**Comment by benilovj** [comment]
> @benilovj this changes the API to return one and only one course per application, which we believe is the correct behaviour. (i.e. Even if a candidate has applied to two courses on the same provider, this should result in two separate applications from the provider's POV)

That sounds right.

On a somewhat related note, I wonder whether `course` is the appropriate word to describe this attribute. Per my understanding:

- the candidate chooses one of the **training locations** where the course is offered
- this is slightly different to **course** (which is the info about the subject, provider, accredited body, qualification etc, and which is associated with some training locations)

Maybe I'm overthinking it...

**Comment by duncanjbrown** [comment]
@benilovj good point. iirc we wanted to unambigiously identify The Thing Which Is Being Applied To. it would be good to hear from providers on what's useful here.

**Comment by chubberlisk** [comment]
> > @benilovj this changes the API to return one and only one course per application, which we believe is the correct behaviour. (i.e. Even if a candidate has applied to two courses on the same provider, this should result in two separate applications from the provider's POV)
> 
> That sounds right.
> 
> On a somewhat related note, I wonder whether `course` is the appropriate word to describe this attribute. Per my understanding:
> 
> * the candidate chooses one of the **training locations** where the course is offered
> * this is slightly different to **course** (which is the info about the subject, provider, accredited body, qualification etc, and which is associated with some training locations)
> 
> Maybe I'm overthinking it...

Seems like there's a discussion to be had! 👍 I'm going to merge this PR in and we can have a chat about this as there is a Trello card about updating the `course` attribute - https://trello.com/c/Yt95CNPy/690-update-course-attribute-within-techdocs.

**Pull request merged**
